# Generated by Django 6.0.4 on 2026-05-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=200, verbose_name='Muallif')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('sold', models.BooleanField(default=False, verbose_name='Sotilgan')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
